"""add hashed_password to users

Revision ID: b0bcc52fe0b3
Revises: dca85285ed0b
Create Date: 2025-12-23 22:49:16.454833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bcc52fe0b3'
down_revision: Union[str, Sequence[str], None] = 'dca85285ed0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.execute(
        "UPDATE users SET hashed_password = 'TEMP_PASSWORD'"
    )

    # 3. Make column NOT NULL
    op.alter_column(
        'users',
        'hashed_password',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
